### ISSUE TITLE
got conflict with onesignal

### ISSUE THREAD

**Issue by manhncse02926** [tolu360/react-native-google-places#122]
May I know have anyone tried to configure  react-natiev-google-placecs and react-native-onesignal ?
I got crash when try to run app on android.

**Comment by tolu360** [comment]
This is most likely due to conflicts in the versions of Google Play Services being pulled in by both packages. You need to normalize the versions to resolve the issue, try the following:

- Make sure you update to v2.5.0 of this package.
- Check the version of Google Play Services in use in the `react-native-onesignal` package, and try to use `project-wide gradle config`. Check the README for how to do that.
- Set `googlePlayServicesVersion` to same version as what the `react-native-onesignal` package currently uses in your  `project-wide gradle config`.
- Clean and rebuild your project.

**Comment by manhncse02926** [comment]
@tolu360 Thank for your reply. I will try to do right now, Later will confirm the result

**Comment by linux08** [comment]
@tolu360  issue still persist .I am currently using the package alongside `react-native-maps` and` react-native-push-notifications` .if i use the below it fails
```  
ext {
      compileSdkVersion   = 26
      targetSdkVersion    = 26
      buildToolsVersion   = "26.1.0"
      supportLibVersion   = "26.1.0"
      googlePlayServicesVersion = "10.2.4"
      androidMapsUtilsVersion = "0.5+"
    }
```
but if i try this  it works 
```
  ext {
      compileSdkVersion   = 26
      targetSdkVersion    = 26
      buildToolsVersion   = "26.1.0"
      supportLibVersion   = "26.1.0"
      googlePlayServicesVersion = "+"
      androidMapsUtilsVersion = "+"
    }
```
Any idea on how i can resolve this.Thanks
