### ISSUE TITLE
RN apps created through expo errors out

### ISSUE THREAD

**Issue by Ramprasathb** [tolu360/react-native-google-places#177]
React native apps created through Expo throw undefined error when using this project. Any plans to support such projects?

**Comment by devlinb** [comment]
> 
> 
> React native apps created through Expo throw undefined error when using this project. Any plans to support such projects?

Expo does not support native modules, so this project cannot ever work with Expo as Expo stands today.

Note: Don't use the Google Places Web SDK in your RN project, as your private API key will be exposed. Your best bet is to create a web service using the Google Places Web SDK that your RN project talks to, and that web service fetches all the data you need and forwards it to your RN app. 

Because of how Google Places is priced, this costs a lot more than doing it natively. If you want to save money, you need to eject from Expo so you can use native modules in your RN project.

**Comment by tolu360** [comment]
You may consider this workflow to enjoy the best of both worlds - https://blog.expo.io/you-can-now-use-expo-apis-in-any-react-native-app-7c3a93041331.

Also consider getting on the latest release, you can further reduce cost by specifying the fields you want results for. Please see #198
