### ISSUE TITLE
PLACES_API_ACCESS_NOT_CONFIGURED

### ISSUE THREAD

**Issue by codal-mpawar** [tolu360/react-native-google-places#199]
PLACES_API_ACCESS_NOT_CONFIGURED error status is not solved help me

**Comment by tolu360** [comment]
The docs (README) are actually really good, please follow them more carefully (line by line). In the meantime, which version are you working with? On which platform/OS are you getting this error? This error shows you do not have permissions properly enabled for your API key in Google cloud console!

**Comment by codal-mpawar** [comment]
I check it all of things also i check permission in API key Google cloud console is every thing is fine

**Comment by prajvalmmf** [comment]
Have you solved that error ? . I am getting same error
Status{statusCode=PLACES_API_ACCESS_NOT_CONFIGURED, resolution=null}'

**Comment by codal-mpawar** [comment]
> Have you solved that error ? . I am getting same error
> Status{statusCode=PLACES_API_ACCESS_NOT_CONFIGURED, resolution=null}'
yes i solve this error 

first you insall beta version then 
gradle.properties in enter a key then 
add meta tag then 
add googleplayversion and all
and use

**Comment by ahmetfarukekinci** [comment]
Hello can you explain how did you solve the problem please? 
I'm getting the same error and I couldnt find anything to solve.

**Comment by mostain-unified** [comment]
Actually the android places api is deprecated and we are not able to create that type of api. So, we created places api which is showing this error. For resolving this when I am trying to implement "implementation 'com.google.android.libraries.places:places:1.0.0'' its not allowing me to genarate build because of this error ==> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
D8: Program type already present: com.google.android.gms.location.places.zza
