### ISSUE TITLE
Apple Store rejected because of IPv6 compatibility issue

### ISSUE THREAD

**Issue by Richou** [tolu360/react-native-google-places#28]
Hello,

I have submitted my app to apple store but they rejected it because of IPv6 compatibility issue.

Have you ever encountered this problem ?
Do you know if Google Places iOS sdk are compatible with IPv6 addresses ?

Thanks for your help
Best regards.

**Comment by tolu360** [comment]
Hi @Richou, I am glad you have completed your app but not so happy to know about the App Store rejection. Whilst I can't confirm if the iOS SDKs are IPv6 compliant, because I am yet to wrap up and submit the app which inspired building out this package, I very much doubt that they are not.

Tons of popular apps use these same SDKs and are on the store. Please inspect other server endpoints your app is making HTTP requests to, for IPv6 compliance. Are you, by any chance, using AWS and the likes? Stumbled on this [thread on StackOverflow](http://stackoverflow.com/questions/37637818/ipv6-app-store-rejection), do check it out.

All the best on resolving this issue and with your app. Cheers!

**Comment by Richou** [comment]
Hi @tolu360 
Thanks for your reponse.
Well I may have found where my problem was, I've forget to add my Archive IPA Bundle ID in the authorized bundle ID in Google Developer Console. I'm waiting for the Apple store's answer.

I will also be very suprised if they are not IPv6 compliant, it's Google after all !

Sorry for the convenience.
Regards !

**Comment by tolu360** [comment]
You are very welcome, and it was no inconvenience at all. I hope that fixes it for you!

**Comment by paulbargaoanu** [comment]
Hi, @Richou!
We are facing the same issue with our submission for review with Apple, however our API keys in the Google Developer Console are not set up to restrict anything, hence no bundle ids have ever been added. As far as I know, you could only add a "Bundle ID in the authorized bundle ID in Google Developer Console" if restrictions are in place. Would you, by any chance, have any suggestions for our scenario that might solve this whole ipv6 situation?
Thanks in advance!
