### ISSUE TITLE
Could not invoke RNGooglePlaces.getAutocompletePredictions

### ISSUE THREAD

**Issue by eman1000** [tolu360/react-native-google-places#48]
Hie bro I am getting this error trying to run the app on android. Everything works fine on ios.

Inside my node-modules folder i checked and saw that react-native-maps is using
  ```
compile "com.google.android.gms:play-services-base:10.2.4"
  compile "com.google.android.gms:play-services-maps:10.2.4"
```

While react native google places
is using 
```
    compile 'com.google.android.gms:play-services-base:10.2.0'
    compile 'com.google.android.gms:play-services-places:10.2.0'
    compile 'com.google.android.gms:play-services-location:10.2.0'
```

React native maps -  
![screen shot 2017-06-08 at 9 16 32 am](https://user-images.githubusercontent.com/16818188/26908117-38054360-4c2b-11e7-8979-4ab5992362bb.png)

**Comment by tolu360** [comment]
Hello @eman1000, this issue is due to the packages pulling in different versions of the `Google Play Services`. As a quick fix, you can definitely force both packages to use the same version of the services.

Do something like this in your `./android/app/build.gradle`:

```groovy
dependencies {
    compile project(':react-native-google-places')
    compile project(':react-native-fcm')
    compile ('com.google.android.gms:play-services-base:10.2.4') {
         force = true;
    }
    compile ('com.google.android.gms:play-services-maps:10.2.4') {
         force = true;
    }
    compile ('com.google.android.gms:play-services-places:10.2.4') {
         force = true;
    }
    compile ('com.google.android.gms:play-services-location:10.2.4') {
        force = true;
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:25.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```
Don't forget to slot in other dependencies unique to your project!

Do a `cd android && ./gradlew clean`, rebuild your project and profit!

Let me know if this fixes the crashes for you. I would bring my own package dependencies up to speed very soon.

Cheers!

**Comment by eman1000** [comment]
@tolu360 you are great bro.. thanks that worked like a charm

**Comment by tolu360** [comment]
@eman1000 you are welcome bro!

**Comment by heckchuckman** [comment]
@tolu360 You amaze again! Awesome work! Thank you.
