### ISSUE TITLE
Reverse Geocoding 

### ISSUE THREAD

**Issue by eman1000** [tolu360/react-native-google-places#87]
Hie, is there a way to get the place name from the latitude and longitude?

**Comment by tolu360** [comment]
Yes, but I'd like to keep this library from getting too bloated - check this other [react-native module/package](https://github.com/devfd/react-native-geocoder) to handle geocoding.

Cheers!

**Comment by bakr-sunbird** [comment]
Call geocode api in google maps and pass your geopoint with your google maps api key.

```javascript 
fetch(`https://maps.googleapis.com/maps/api/geocode/json?latlng=${}&key=${}`)
	.then(res => res.json())
	.then((json) => {
		if (json.status !== 'OK') {
			throw new Error(`Geocode error: ${json.status}`);
		}
	return json;
});
```

**Comment by agrison** [comment]
Is there any chance you would expose this [getFromLocationName(String locationName, int maxResults)](https://developer.android.com/reference/android/location/Geocoder.html#getFromLocationName(java.lang.String, int)) method.

The other react-native module you provided just have a Google fallback, besides you need to expose your key in the Javascript files.

Curiously there is an [open bug](https://issuetracker.google.com/issues/35828699) at Google for this since more than 15 month and it hasn't been fixed yet.

**Comment by mithlesh-pantelwar** [comment]
use this http://maps.googleapis.com/maps/api/geocode/json?latlng=18.5078494,37.0166834&sensor=false 
api
